You wrote on Discord that you need more quotes. I hope you like these…
nhcarrigan/inspirationBot pull request #77
Opened 2022-04-10 10:43 UTC by loui-gh

… ones :)

Signed-off-by: Loui <Louiadmin@protonmail.com>

# Pull Request

## Description:

Added 3 new quotes.

## Related Issue:

Not related to an issue, rather a response to your request on Discord for more quotes.

Closes #XXXXX

2022-04-10 14:37 UTC, nhcarrigan requested changes

2022-04-10 14:37 UTC, nhcarrigan commented on src/config/QuoteList.ts
> +    author: "Virginia Woolf",
```suggestion
    text: "Life is not a series of gig lamps symmetrically arranged;\nlife is a luminous halo, a semitransparent envelope surrounding us\nfrom the beginning of consciousness to the end.",
    author: "Virginia Woolf",
```
The bot is configured to parse `\n` for line breaks 🙂

2022-07-21 16:32 UTC, zayidmohamedy reviewed
👍

2022-07-31 20:50 UTC, naomi-lgbt approved these changes
Went ahead and committed the changes myself so we can get this in.

2022-07-31 20:50 UTC, merged

2022-07-31 20:51 UTC, naomi-lgbt commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.nhcarrigan.com)